#!/usr/bin/env node

//const puppeteer = require('puppeteer');

const COOKIE_DIR = '/var/www/temp-cookies';
const WAIT_SECS = 5;
const USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0';

const puppeteer = require('puppeteer-extra')
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin())
const argv = require("yargs").option('url', {
    alias: 'u',
    default: false
  }).argv;
const fs = require("fs").promises;
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

const options = { 
	headless: true,
	args: ['--no-sandbox', '--disable-setuid-sandbox']
};
const headers = {
  'User-Agent': USER_AGENT
}

let url = 'https://www.example.org';



if (argv.url) {
  url = argv.url;
}

(async () => {
  const browser = await puppeteer.launch(options);
  const page = await browser.newPage();
  await page.setExtraHTTPHeaders(headers);

  const ts = Date.now();
  const cookieFn = `cookies-${ts}.json`;
  const cookiesFilePath = [COOKIE_DIR, cookieFn].join('/');

  await page.goto(url);

  const remoteCookies = await page.cookies();
  await fs.writeFile(cookiesFilePath, JSON.stringify(remoteCookies));
  const cookies = JSON.parse(await fs.readFile(cookiesFilePath));
  await	page.waitForTimeout(20);
  await page.setCookie(...cookies);
  await	page.waitForTimeout(WAIT_SECS*1000);

  let html = await page.content();
  if (typeof html === 'string') {
    html = html.replace(/<link[^>]*?>/g, '').replace(/<style[^>]*?>[^§]*?<\/style>/g, '');
  }
  const dom = new JSDOM(html);	
  const core = dom.window.document.querySelector('body');
  const titleEl = dom.window.document.querySelector('title');
  let title = '';
  if (titleEl) {
    title = titleEl.textContent;
  }
  if (core) {
    const removeNodes = core.querySelectorAll('script,style,iframe,svg,path');
    if (removeNodes) {
      for (const rm of removeNodes) {
        rm.parentNode.removeChild(rm);
      }
    }
    html = core.innerHTML;	
  }
  console.log('<head><title>'+title+'</title></head><body>'+html+'</body>');

  await browser.close();
})();
